export const SET_ACTIVE_PAGE = "SET_ACTIVE_PAGE";
export const SET_LOGIN = "SET_LOGIN";
export const SET_LOGOUT = "SET_LOGOUT";
export const SET_LOADING = "SET_LOADING";
export const SET_SOCKET = "SET_SOCKET";
export const SET_ACTIVE_MAIN_COMPONENT = "SET_ACTIVE_MAIN_COMPONENT";
export const SET_ACTIVE_CHAT = "SET_ACTIVE_CHAT";
export const SET_CHAT_DATA = "SET_CHAT_DATA";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const SET_IS_PARTNER_TYPING = "SET_IS_PARTNER_TYPING"
export const ADD_MESSAGE = "ADD_MESSAGE"
export const REMOVE_MESSAGE = "REMOVE_MESSAGE"
export const SET_ARRIVED_NEW_MESSAGES = "SET_ARRIVED_NEW_MESSAGES"
export const REMOVE_ARRIVED_NEW_MESSAGES = "REMOVE_ARRIVED_NEW_MESSAGES"
export const SET_MY_CHATS = "SET_MY_CHATS"
export const SET_ACTIVE_CHAT_MESSAGES = "SET_ACTIVE_CHAT_MESSAGES"
export const SET_ACTIVE_CHAT_NEW_MESSAGES = "SET_ACTIVE_CHAT_NEW_MESSAGES"
export const SET_NEW_SEEN_MARKED_MESSAGES = "SET_NEW_SEEN_MARKED_MESSAGES"
export const SET_NEW_RECEIVED_MARKED_MESSAGES = "SET_NEW_RECEIVED_MARKED_MESSAGES"








